server:
  port: 8081
  error:
    path: /user/error
    whitelabel:
      enabled: false
jwt:
  secret: MbSm+cbkvS7Mo9V/ingpKv6Gtfj6E9ZD5DvSTszDslEoLYxJNGNPBlo9bD83kJOc

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myappdb
    username: someuser
    password: someuser-pw
  jpa:
    #https://www.asciiart.eu/text-to-ascii-art
    generate-ddl: true #true for init
    show-sql: true
    hibernate:
      ddl-auto: update #The values create, create-drop, validate, and update. update for init
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        format_sql: true
  sql:
     init:
       mode: never
       continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: someuser@mail.com
    password: someuser-pw #get from https://myaccount.google.com/security  https://www.youtube.com/watch?v=FYq9yWgrO8o
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
logging:
  level:
    nl.basjes.parse.useragent.utils.YauaaVersion: ERROR
